### ISSUE TITLE
Duo MIDI-CV bend range (linux)

### ISSUE THREAD

**Issue by ContemporaryInsanity** [anlexmatos/MIDI-Delexander#1]
Bend ranges +/- 2 to +/- 48 have no effect on bent pitch output, bend ranges +/- 60 to +/- 96 have identical extreme effect.  Tested with both a M-Audio Oxygen 25 and Edirol PCR-300.

**Comment by xandramax** [comment]
That's what I get for making a change just before release! The newest release should have this fixed; let me know if you still have problems.
